### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by MrAlgo** [megakid/ha_octopus_intelligent#31] opened 2024-01-21 07:01 UTC
Hi, been using this for a long time now but has stopped working sometime in the last week or so. Anyone else found the same? My charging slot, regardless of my intelligent slot, has reverted to the standard 23:30-05:30.

**Comment by Raptotype** [comment] 2024-01-21 07:36
I have a similar issue. The slots don’t always update. I have a slot assigned in the octopus app but the integration shows no slot.

**Comment by ASomerN** [comment] 2024-01-21 08:18
Pretty sure this is a duplicate of: https://github.com/megakid/ha_octopus_intelligent/issues/30
I'm not sure if this is getting any attention from @megakid 
The other issue raised references this working: https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/
It also mentions rate limiting, which fits with the system flipping between working and sensors going unavailable.

**Comment by MrAlgo** [comment] 2024-01-21 08:37
Thanks. I should have checked that thread first! I'll check out the other intergration.

**Comment by MarkTarry** [comment] 2024-01-23 21:13
I'm not sure, but is this the same issue as https://github.com/megakid/ha_octopus_intelligent/issues/32 ?

**Comment by Paulholloway** [comment] 2024-01-28 07:45
I'm finding similar issues too. Is there an alternative out there for HA?

**Comment by ASomerN** [comment] 2024-01-28 10:28
> I'm finding similar issues too. Is there an alternative out there for HA?

https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/

Doesn't have everything but does detect if you are in a dispatch slot

**Comment by Paulholloway** [comment] 2024-02-02 16:32
Excellent point! The bottlecapdave integration has the same intelligent entities, and it's possible to scrape the charge slots out of the state attributes. I don't think this integration offers much more?

**Closed** 2024-02-04 00:19 UTC
