### ISSUE TITLE
All entities randomly, become unavailable.

### ISSUE THREAD

**Issue by spinecho31** [megakid/ha_octopus_intelligent#30] opened 2023-12-07 02:36 UTC
Integration randomly becomes unavailable, so far I couldn't not isolate the cause.
Using the latest version 1.6.2

How can I help you troubleshoot this?
![Screenshot_20231206-214740](https://github.com/megakid/ha_octopus_intelligent/assets/54399974/f15a3e6d-1ae9-4a8e-a0d5-6386bd6578fe)
![Screenshot_20231207-022227](https://github.com/megakid/ha_octopus_intelligent/assets/54399974/a34ff269-96a5-4fec-94b3-49809cec801c)

**Comment by jimdholmes** [comment] 2023-12-08 11:56
Hi, not sure if this related or if it hlps however I am having issues with three seperate integrations since upgrading to 2023.12 yesterday, this being one of them. The issue I am seeing states "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble" for each of the integrartions that havev stopped working.

The other two integrations are:

  - Tesla Custom Integration 
  - Tapo Custom Integration

Both of these are displaying the same error message as above. 

Might just be coincidence but my HA Octopus Intelligent, Tesla and Tapo integrations all stopped working with the same error message on upgrading to 2023.12 after a restart.

**Comment by jimdholmes** [comment] 2023-12-08 18:04
Quick update, rolled back to a previous version of HA and all working again 😁

**Comment by Stewbo1** [comment] 2023-12-13 18:38
I also have this issue since upgrading HA to 2023.12.1.

**Comment by BadgerLoaf** [comment] 2023-12-18 16:08
I'm seeing the same, irregular dropouts. The following history chart shows the missing data over the past couple of days (the grey missing areas).

<img width="651" alt="Screenshot 2023-12-18 at 16 04 39" src="https://github.com/megakid/ha_octopus_intelligent/assets/108699847/7687af41-faa6-4ec5-9a44-40ad29db9dfa">

HA: 2023.12.3
Octopus Intelligent: v1.6.2

@megakid - Are you aware of any issues? Do you need us to take any logs etc?

**Comment by goul** [comment] 2023-12-18 17:43
Just to confirm I'm seeing the same on HA 2023.12.3. With debug on all I can see in logs is :

2023-12-18 17:39:56.895 DEBUG (MainThread) [custom_components.octopus_intelligent] Setting up Octopus Intelligent System component
2023-12-18 17:40:26.903 DEBUG (MainThread) [custom_components.octopus_intelligent.octopus_intelligent_system] Finished fetching Octopus Intelligent data in 30.004 seconds (success: False)

Tried removing and adding through HACS, but no joy.

Let me know if I can do anything to help.

**Comment by nickcj931** [comment] 2023-12-18 17:44
Just doing my updates and came across same issue when trying to update home assistant to 2023.12.3 from 2023.10.1, although following a restore it still will not initialise the integration. Even before the update I did notice that there are a lot more gaps in the data shown as per @BadgerLoaf. 

HA: 2023.10.1 (rollback from failed attempt on 2023.12.3) still not working
Octopus Intelligent: v1.6.2

I am seeing a few warnings in the logs relating to the integration:

```
Logger: py.warnings
Source: runner.py:186
First occurred: 16:47:27 (1 occurrences)
Last logged: 16:47:27

/usr/local/lib/python3.11/asyncio/base_events.py:1907: RuntimeWarning: coroutine 'OctopusIntelligentSystem.start' was never awaited handle = self._ready.popleft()

Logger: homeassistant.config_entries
Source: config_entries.py:441
First occurred: 16:47:57 (1 occurrences)
Last logged: 16:47:57

Config entry '' for octopus_intelligent integration not ready yet: Error communicating with Octopus GraphQL API: ; Retrying in background

Logger: py.warnings
Source: runner.py:186
First occurred: 16:47:27 (5 occurrences)
Last logged: 16:50:55

/usr/local/lib/python3.11/asyncio/base_events.py:1907: RuntimeWarning: coroutine 'OctopusIntelligentSystem.start' was never awaited handle = self._ready.popleft()
/usr/local/lib/python3.11/asyncio/base_events.py:1923: RuntimeWarning: coroutine 'OctopusIntelligentSystem.start' was never awaited handle = None # Needed to break cycles when an exception occurs.

```


Things attempted:
- Reverted back to previous HA version 2023.10.1 - integration does not start
- Re-downloaded the Octopus Intelligent integration - integration does not start
- Deleted the integration at previous version 1.6.1 - full system reboot - integration does not start

Have Octopus changed something? or is the service down from them perhaps?

**Comment by nickcj931** [comment] 2023-12-18 17:47
I've just noticed that my friends integration has been down since 1545 UK time 18th Dec today as well.... so seems a mere coincidence that it felt that HA 2023.12.3 broke this integration. 

It seems that either:
1. Octopus have an outage
2. Octopus have made some changes their end which broke the integration ?

Thoughts?

**Comment by gdotp01** [comment] 2023-12-18 17:59
@nickcj931 mine became unavailable at the same time. I suspect it’s an octopus issue.

**Comment by Ryderbrew** [comment] 2023-12-18 18:59
Same boat here, went down at 15:44. I wonder if its a regional octopus intel server issue. I'm in the st7 are, where are you guys located.

**Comment by garethcook** [comment] 2023-12-18 19:36
Ditto. Seeing this, and has been working OK for the past week.

Logger: py.warnings
Source: runner.py:188
First occurred: 19:32:07 (3 occurrences)
Last logged: 19:33:59

/usr/local/lib/python3.11/asyncio/base_events.py:1926: RuntimeWarning: coroutine 'OctopusIntelligentSystem.start' was never awaited handle = None # Needed to break cycles when an exception occurs.
/usr/local/lib/python3.11/asyncio/base_events.py:1910: RuntimeWarning: coroutine 'OctopusIntelligentSystem.start' was never awaited handle = self._ready.popleft()

**Comment by drnichols** [comment] 2023-12-18 20:10
Same here although I've tried an alternative Octopus integration which is working, suggesting the API is working (although may have changed functionality?). https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy

**Comment by garethcook** [comment] 2023-12-18 20:19
I have that add-on also, from before it had Intelligent support. That's also failing for me.

**Comment by drnichols** [comment] 2023-12-18 20:23
I just tried to re-add the integration with my details which returned already configured and then re-initialised the integration which is now working again so perhaps a transient issue.

**Comment by gdotp01** [comment] 2023-12-18 20:31
Yep it’s back up and I’d changed nothing.

**Comment by BadgerLoaf** [comment] 2023-12-18 20:58
Yes, that was the biggest drop for a while, but not sure if the cause will be any different that all the others seen recently.

<img width="469" alt="Screenshot 2023-12-18 at 20 55 42" src="https://github.com/megakid/ha_octopus_intelligent/assets/108699847/0d699e6c-2778-409d-b5a9-0e18a7bc648a">

**Comment by nickcj931** [comment] 2023-12-19 08:46
> Same boat here, went down at 15:44. I wonder if its a regional octopus intel server issue. I'm in the st7 are, where are you guys located.

Im in Powys Wales. 

But didn't think they had regional servers since uk doesn't have that type of datacenter setup as we are that small. Maybe Lon and Man for example. 

But the drop outs are getting worse and worse. 

I wonder if they are hitting the API limits perhaps? Companies do this all the time, create and offer an API and don't actually think what happens when it needs to scale and it starts to cost serious ££ ....  
I just hope the don't rug pull it as its been such a great service and I literally use Octopus because of it being so feature rich.

**Comment by nickcj931** [comment] 2023-12-19 08:54
I've found this discussion over on the [BottlecapDave ](https://github.com/BottlecapDave)/
[HomeAssistant-OctopusEnergy](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy) that @drnichols mentioned.

Seems like they have introduced rate limit after all, although it seems they are talking about the Home Mini - I wonder if that is a platform wide rate limit on whole API Kraken or just for Home Mini related data? no idea

I wouldn't have a clue how to check the code on this integration, but wonder if its "gapping out" because of this limiter (yesterday being an odd ball where perhaps Octopus did maintenance), and a polling rate needs to be adjusted in the app?

**Comment by G8YTZ** [comment] 2024-01-08 07:54
Same issue here as above.

**Comment by MarkTarry** [comment] 2024-01-13 21:07
It seems that I'm also facing an issue with entities falling back to "unavailable" state - it's happening with the `megakid/ha_octopus_intelligent` integration entities:

![image](https://github.com/megakid/ha_octopus_intelligent/assets/155492324/e9efa5f4-5811-4327-91be-368aa6a5dbc1)

But, interestingly, it's not happening with the equivalent `BottlecapDave/HomeAssistant-OctopusEnergy` integration entities:

![image](https://github.com/megakid/ha_octopus_intelligent/assets/155492324/052e84e9-7160-4bcd-9f80-ea2d4abcffa3)

So, if this was API throttling, then the other integration is somehow handling it.

**Comment by G8YTZ** [comment] 2024-01-13 21:15
I saw a new issue today with the entities showing particular times for the start of the next off-peak period, but the octopus app was showing different times.Sent from my Remington Rand UNIVACwww.g8ytz.com On 13 Jan 2024, at 21:07, MarkTarry ***@***.***> wrote:﻿
It seems that I'm also facing an issue with entities falling back to "unavailable" state - it's happening with the megakid/ha_octopus_intelligent integration entities:
image.png (view on web)
But, interestingly, it's not happening with the equivalent BottlecapDave/HomeAssistant-OctopusEnergy integration entities:
image.png (view on web)
So, if this was API throttling, then the other integration is somehow handling it.

**Comment by andyvee69** [comment] 2024-01-13 21:18
Not only is there rate limiting in place, Octopus are now blocking requests that do not have a suitable request header.

**Comment by bensebborn** [comment] 2024-01-14 12:43
Same issue here. Lots of drop outs which are causing my “end” automations to run multiple times. 

![Uploading IMG_4732.png…]()

**Comment by Paulholloway** [comment] 2024-01-14 14:08
I'm finding that, predominantly, `octopus_intelligent_offpeak_end` is unavailable for quite some time.  From the history, I find that the other entities do drop out but (as I write) they've all a value.  Fortunately, at 23:30:01 I more often than not (this week) `octopus_intelligent_offpeak_end` has a value and so my automations tend to run.  I'm hoping a tweak to my automation to be less sensitive to the entity being unavailable is a short term solution.  Ideally, I'd quite like it to be more stable / available.  

My log has:


```
2024-01-14 07:26:48.674 ERROR (MainThread) [custom_components.octopus_intelligent.octopus_intelligent_system] Error fetching Octopus Intelligent data: Error communicating with Octopus GraphQL API:

2024-01-14 01:07:34.674 ERROR (MainThread) [custom_components.octopus_intelligent.octopus_intelligent_system] Error fetching Octopus Intelligent data: Error communicating with Octopus GraphQL API: 
```

Hopefully that's (A) related and (B) some use?

**Comment by sparkyhughes** [comment] 2024-01-16 15:21
I’m seeing the same issues too. 
Is this being worked on or do we need to consider using a different integration? 1.6.2 came out June last year.

**Comment by G8YTZ** [comment] 2024-01-16 15:31
> Hi, not sure if this related or if it helps however I am having issues with three seperate integrations since upgrading to 2023.12 yesterday, this being one of them. The issue I am seeing states "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble" for each of the integrartions that have stopped working.
> 
> The other two integrations are:
> 
> * Tesla Custom Integration
> * Tapo Custom Integration
> 
> Both of these are displaying the same error message as above.
> 
> Might just be coincidence but my HA Octopus Intelligent, Tesla and Tapo integrations all stopped working with the same error message on upgrading to 2023.12 after a restart.

Yes, I have see issues with other integrations, particularly the PowerWall, implying a "breaking change" has caused the issue. I don't use the Tesla car integration, though I have installed it and it is currently disabled. If you restart HA it fixes the issue (reload does not), it appears to be a process that stops randomly and occasionally restarts. I'm running HA on an Intel NUC Celeron.

**Comment by drnichols** [comment] 2024-01-17 16:20
I've been having issues with the entities becoming unavailable or just showing the incorrect values for the past couple of months. I've installed this integration too (https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/) which is not as rich but is not having the same issues. I've updated my sensors in HA to use the status of which ever integration is working at the time (using or logic).

**Comment by bensebborn** [comment] 2024-01-20 09:08
@megakid any suggestions/workarounds?

**Comment by daknightuk** [comment] 2024-01-23 15:17
Same issue here, was working fine on  Core 2024.1.5 ,Supervisor 2023.12.1 
I get the impression that Octopus has realised that some people are creating automations which use their "car charging slots" to charge solar battery storage from grid and run high wattage appliances like the washing machine, tumble dryer etc etc... as their intelligent octopus tariff is 0.07 Kwh

**Comment by megakid** [comment] 2024-01-23 21:47
Apologies for radio silence- I've not been available to look at this (new job and baby in the house). I'll try to take a look but this is a change on Octopus's end that I'll need to work with and/or around.

Thanks for your patience!

**Comment by MartinJSa** [comment] 2024-01-26 14:16
What's the default poll interval for this integration? I'm wondering if we need to be 'good API citizens' and make the polling less frequent? A small change here could help if Octopus are struggling with API load, and isn't likely to make a big difference to how well our automations work?

**Comment by MrAlgo** [comment] 2024-01-26 14:25
Not sure what the difference is between these integrations but I tried this instead (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy) and it works well. Megakid is above and the new one is below. Had to adjust my automations etc but working again now.

![image](https://github.com/megakid/ha_octopus_intelligent/assets/30338279/dc9ad151-312a-426e-a8ee-905ee3e94cb2)

Congrats on the new arrival.

**Comment by daknightuk** [comment] 2024-01-26 17:52
> Not sure what the difference is between these integrations but I tried this instead (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy) and it works well. Megakid is above and the new one is below. Had to adjust my automations etc but working again now.
> 
> ![image](https://private-user-images.githubusercontent.com/30338279/300012040-dc9ad151-312a-426e-a8ee-905ee3e94cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTE2NTksIm5iZiI6MTcwNjI5MTM1OSwicGF0aCI6Ii8zMDMzODI3OS8zMDAwMTIwNDAtZGM5YWQxNTEtMzEyYS00MjZlLWE4ZWUtOTA1ZWUzZTk0Y2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE3NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNTllZjNlZTgzYjIzYmQ3N2QzMmE0NTE1ZDU1ZDk2ZDQxMDRlMTFmMWIyY2NiOTRhNDE0MGFkMWY1YTE4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.roGeFep8d1ozviUqjsGmEc086DkzhoD0kgvniZG1Z5Y)
> 
> Congrats on the new arrival.

I didn't realise that the BottlecapDave integration had the intelligent smart charging in already. I just wonder why are there 2 different integrations doing similar things..

**Comment by G8YTZ** [comment] 2024-01-26 18:04
> > Not sure what the difference is between these integrations but I tried this instead (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy) and it works well. Megakid is above and the new one is below. Had to adjust my automations etc but working again now.
> > ![image](https://private-user-images.githubusercontent.com/30338279/300012040-dc9ad151-312a-426e-a8ee-905ee3e94cb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyOTE2NTksIm5iZiI6MTcwNjI5MTM1OSwicGF0aCI6Ii8zMDMzODI3OS8zMDAwMTIwNDAtZGM5YWQxNTEtMzEyYS00MjZlLWE4ZWUtOTA1ZWUzZTk0Y2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDE3NDkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNTllZjNlZTgzYjIzYmQ3N2QzMmE0NTE1ZDU1ZDk2ZDQxMDRlMTFmMWIyY2NiOTRhNDE0MGFkMWY1YTE4ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.roGeFep8d1ozviUqjsGmEc086DkzhoD0kgvniZG1Z5Y)
> > Congrats on the new arrival.
> 
> I didn't realise that the BottlecapDave integration had the intelligent smart charging in already. I just wonder why are there 2 different integrations doing similar things..

I too have swapped over to BottlecapDave, but today that became unavailable too, so it must be an issue at the Octopus end or perhaps we are sending too many requests over? THE advantage of the Octopus Intelligent integration is it give you the 1, 2 and 3 hour slot indicators.

**Comment by DragonQ** [comment] 2024-01-28 03:41
> I didn't realise that the BottlecapDave integration had the intelligent smart charging in already. I just wonder why are there 2 different integrations doing similar things..
Yes for some reason the BottlecapDave integration doesn't have issues with sensors turning unavailable like this one does.

However, this one has 2 advantages: it has a "next offpeak start" sensor, and it updates dispatch slots way more accurately. I suspect the latter might be due to it polling the API more frequently, which could also be the cause of the constant "unavailable" issues?

**Comment by megakid** [comment] 2024-01-28 10:49
This integration polls the API every 5 mins (see interval here https://github.com/megakid/ha_octopus_intelligent/blob/main/custom_components/octopus_intelligent/octopus_intelligent_system.py) which feels quite conservative but is obviously still a problem.

I did see someone say a header is required now which I need to research. I will try to get to it tonight

**Comment by megakid** [comment] 2024-02-04 00:19
Hopefully this is fixed with https://github.com/megakid/ha_octopus_intelligent/releases/tag/v1.6.3

**Closed by megakid** 2024-02-04 00:19 UTC
